include ".buildkit/.scalafmt.shared.conf"

runner.dialect = "scala213"

project.excludePaths = [
  "glob:**/src/*/scala-3/**" #TODO[Build] specify folder-specific rules (pretty much just runner.dialect)
  "glob:**/src/*/scala/com/raquo/airstream/combine/generated/**"
  "glob:**/src/*/scala/com/raquo/airstream/extensions/{TupleSignals.scala,TupleStreams.scala,OptionTupleObservables.scala}"
]

docstrings.style = SpaceAsterisk
