import sbt._

import java.io.File

case class GenerateOptionTupleObservables(
  classNamePattern: Int => String, // N => className
  fileName: String,
  sourceDir: File,
  from: Int,
  to: Int
) extends SourceGenerator(
  sourceDir / "scala" / "com" / "raquo" / "airstream" / "extensions" / fileName
) {

  override def apply(): Unit = {
    line("package com.raquo.airstream.extensions")
    line()
    line("import com.raquo.airstream.core.{BaseObservable, Observable, Signal}")
    line("import com.raquo.airstream.state.StrictSignal")
    line()
    line("// #Warning do not edit this file directly, it is generated by GenerateOptionTupleObservables.scala")
    line()
    line("// These mapSomes and splitOptions helpers are implicitly available on observables")
    line("// (signals and streams) of tuples of options")
    line()
    for (n <- from to to) {
      enter(s"class ${classNamePattern(n)}[${tupleType(n)}, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (${tupleType(n, "Option[T", "]")})]) extends AnyVal {", "}") {
        line()
        line("/** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */")
        enter(s"def mapSomes[Out](project: (${tupleType(n)}) => Out): Self[Option[Out]] = {", "}") {
          enter("observable", "") {
            enter(".map {", "}") {
              line(s"case (${tupleType(n, "Some(v", ")")}) => Some(project(${tupleType(n, "v")}))")
              line("case _ => None")
            }
            line(".asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]")
            line(".distinctNoneOnly")
          }
        }
        line()
        line("/** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */")
        enter(s"def tupledSomes: Self[Option[(${tupleType(n)})]] = {", "}") {
          line(s"mapSomes((${(1 to n).map(_ => "_").mkString(", ")}))")
        }
        line()
        line("/** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */")
        enter(s"def splitOptions[Out](project: (${tupleType(n, "StrictSignal[T", "]")}) => Out): Signal[Option[Out]] = {", "}") {
          enter("observable", "") {
            enter(".map {", "}") {
              line(s"case (${tupleType(n, "Some(v", ")")}) => Some((${tupleType(n, "v")}))")
              line("case _ => None")
            }
            line(s".asInstanceOf[BaseObservable[Self, Option[(${tupleType(n)})]]] // #TODO[types]")
            enter(".splitOption { values =>", "}") {
              line(s"project(${tupleType(n, "values.map(_._", ")")})")
            }
          }
        }
      }
      line()
      line("// --")
      line()
    }
  }
}