package com.raquo.airstream.extensions

import com.raquo.airstream.core.{BaseObservable, Observable, Signal}
import com.raquo.airstream.state.StrictSignal

// #Warning do not edit this file directly, it is generated by GenerateOptionTupleObservables.scala

// These mapSomes and splitOptions helpers are implicitly available on observables
// (signals and streams) of tuples of options

class OptionTupleObservable2[T1, T2, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2)) => Some(project(v1, v2))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2)]] = {
    mapSomes((_, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2)) => Some((v1, v2))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2))
      }
  }
}

// --

class OptionTupleObservable3[T1, T2, T3, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3)) => Some(project(v1, v2, v3))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3)]] = {
    mapSomes((_, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3)) => Some((v1, v2, v3))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3))
      }
  }
}

// --

class OptionTupleObservable4[T1, T2, T3, T4, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4)) => Some(project(v1, v2, v3, v4))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4)]] = {
    mapSomes((_, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4)) => Some((v1, v2, v3, v4))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4))
      }
  }
}

// --

class OptionTupleObservable5[T1, T2, T3, T4, T5, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5)) => Some(project(v1, v2, v3, v4, v5))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5)]] = {
    mapSomes((_, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5)) => Some((v1, v2, v3, v4, v5))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5))
      }
  }
}

// --

class OptionTupleObservable6[T1, T2, T3, T4, T5, T6, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6)) => Some(project(v1, v2, v3, v4, v5, v6))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6)]] = {
    mapSomes((_, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6)) => Some((v1, v2, v3, v4, v5, v6))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6))
      }
  }
}

// --

class OptionTupleObservable7[T1, T2, T3, T4, T5, T6, T7, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7)) => Some(project(v1, v2, v3, v4, v5, v6, v7))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7)]] = {
    mapSomes((_, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7)) => Some((v1, v2, v3, v4, v5, v6, v7))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7))
      }
  }
}

// --

class OptionTupleObservable8[T1, T2, T3, T4, T5, T6, T7, T8, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8)]] = {
    mapSomes((_, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8)) => Some((v1, v2, v3, v4, v5, v6, v7, v8))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8))
      }
  }
}

// --

class OptionTupleObservable9[T1, T2, T3, T4, T5, T6, T7, T8, T9, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9))
      }
  }
}

// --

class OptionTupleObservable10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10))
      }
  }
}

// --

class OptionTupleObservable11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11))
      }
  }
}

// --

class OptionTupleObservable12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12))
      }
  }
}

// --

class OptionTupleObservable13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13))
      }
  }
}

// --

class OptionTupleObservable14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14))
      }
  }
}

// --

class OptionTupleObservable15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15))
      }
  }
}

// --

class OptionTupleObservable16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15], Option[T16])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15], StrictSignal[T16]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15), values.map(_._16))
      }
  }
}

// --

class OptionTupleObservable17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15], Option[T16], Option[T17])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15], StrictSignal[T16], StrictSignal[T17]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15), values.map(_._16), values.map(_._17))
      }
  }
}

// --

class OptionTupleObservable18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15], Option[T16], Option[T17], Option[T18])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15], StrictSignal[T16], StrictSignal[T17], StrictSignal[T18]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15), values.map(_._16), values.map(_._17), values.map(_._18))
      }
  }
}

// --

class OptionTupleObservable19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15], Option[T16], Option[T17], Option[T18], Option[T19])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15], StrictSignal[T16], StrictSignal[T17], StrictSignal[T18], StrictSignal[T19]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15), values.map(_._16), values.map(_._17), values.map(_._18), values.map(_._19))
      }
  }
}

// --

class OptionTupleObservable20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15], Option[T16], Option[T17], Option[T18], Option[T19], Option[T20])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19), Some(v20)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15], StrictSignal[T16], StrictSignal[T17], StrictSignal[T18], StrictSignal[T19], StrictSignal[T20]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19), Some(v20)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15), values.map(_._16), values.map(_._17), values.map(_._18), values.map(_._19), values.map(_._20))
      }
  }
}

// --

class OptionTupleObservable21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15], Option[T16], Option[T17], Option[T18], Option[T19], Option[T20], Option[T21])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19), Some(v20), Some(v21)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15], StrictSignal[T16], StrictSignal[T17], StrictSignal[T18], StrictSignal[T19], StrictSignal[T20], StrictSignal[T21]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19), Some(v20), Some(v21)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15), values.map(_._16), values.map(_._17), values.map(_._18), values.map(_._19), values.map(_._20), values.map(_._21))
      }
  }
}

// --

class OptionTupleObservable22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, Self[+_] <: Observable[?]](private val observable: BaseObservable[Self, (Option[T1], Option[T2], Option[T3], Option[T4], Option[T5], Option[T6], Option[T7], Option[T8], Option[T9], Option[T10], Option[T11], Option[T12], Option[T13], Option[T14], Option[T15], Option[T16], Option[T17], Option[T18], Option[T19], Option[T20], Option[T21], Option[T22])]) extends AnyVal {

  /** If every Option is defined, maps their values; otherwise yields None. Consecutive None events are collapsed into one. */
  def mapSomes[Out](project: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) => Out): Self[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19), Some(v20), Some(v21), Some(v22)) => Some(project(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[Out]]] // #TODO[types]
      .distinctNoneOnly
  }

  /** If every Option is defined, combines their values into a tuple; otherwise yields None. Consecutive None events are collapsed into one. */
  def tupledSomes: Self[Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22)]] = {
    mapSomes((_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _))
  }

  /** Like .splitOption but for a tuple of Options: only yields Some(project) when every Option is defined, providing a StrictSignal for each value (None otherwise). */
  def splitOptions[Out](project: (StrictSignal[T1], StrictSignal[T2], StrictSignal[T3], StrictSignal[T4], StrictSignal[T5], StrictSignal[T6], StrictSignal[T7], StrictSignal[T8], StrictSignal[T9], StrictSignal[T10], StrictSignal[T11], StrictSignal[T12], StrictSignal[T13], StrictSignal[T14], StrictSignal[T15], StrictSignal[T16], StrictSignal[T17], StrictSignal[T18], StrictSignal[T19], StrictSignal[T20], StrictSignal[T21], StrictSignal[T22]) => Out): Signal[Option[Out]] = {
    observable
      .map {
        case (Some(v1), Some(v2), Some(v3), Some(v4), Some(v5), Some(v6), Some(v7), Some(v8), Some(v9), Some(v10), Some(v11), Some(v12), Some(v13), Some(v14), Some(v15), Some(v16), Some(v17), Some(v18), Some(v19), Some(v20), Some(v21), Some(v22)) => Some((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22))
        case _ => None
      }
      .asInstanceOf[BaseObservable[Self, Option[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22)]]] // #TODO[types]
      .splitOption { values =>
        project(values.map(_._1), values.map(_._2), values.map(_._3), values.map(_._4), values.map(_._5), values.map(_._6), values.map(_._7), values.map(_._8), values.map(_._9), values.map(_._10), values.map(_._11), values.map(_._12), values.map(_._13), values.map(_._14), values.map(_._15), values.map(_._16), values.map(_._17), values.map(_._18), values.map(_._19), values.map(_._20), values.map(_._21), values.map(_._22))
      }
  }
}

// --

